.Dd January 10, 2025
.Dt TR2CYR
.
.Sh NAME
.Nm tr2cyr
.Nd Convert transliteration
into cyrillic text
.
.Sh DESCRIPTION
Just simple tool
I made
because I have
nothing to do.
.
.Pp
Well,
because of meeting some comments
about non-intuitive table of translation,
I should say that
.Nm
is intended to be used
first of all
in tools in
.Em my
environment,
when I don't have access
to Russian layout.
The purpose of this tool
is to provide an ability
to make any combination
of cyrillic characters.
Also,
I didn't want
to complicate the tool.
So I created
.Nm
that way
in the end.
.
.Sh SEE ALSO
.Xr tr2cyr 1 ,
.Xr tr2cyr 3
