.Dd January  7, 2025
.Dt TR2CYR
.Os
.
.Sh NAME
.Nm tr2cyr
.Nd Convert transliteration
into cyrillic text
.
.Sh SYNOPSIS
.Nm
.
.Sh DESCRIPTION
.Nm
is a simple tool
to convert transliteration
into cyrillic text.
It reads
.Xr stdin 3
and prints output
to its
.Xr stdout 3 .
If first char
of the sequence
is uppercase,
then result
will be uppercase too.
.
.Pp
.Nm
converts
according to the table below
.Bl -tag -width Ds
.It Sy a 
а
.It Sy b
б
.It Sy v
в
.It Sy g
г
.It Sy d
д
.It Sy e
е
.It Sy yo
ё
.It Sy yz
ж
.It Sy z
з
.It Sy i
и
.It Sy j
й
.It Sy k
к
.It Sy l
л
.It Sy m
м
.It Sy n
н
.It Sy o
о
.It Sy p
п
.It Sy r
р
.It Sy s
с
.It Sy t
т
.It Sy u
у
.It Sy f
ф
.It Sy h
х
.It Sy c
с
.It Sy yc
ч
.It Sy ys
ш
.It Sy yg
щ
.It Sy y"
ъ
.It Sy yi
ы
.It Sy y'
ь
.It Sy ye
э
.It Sy yu
ю
.It Sy ya
я
.El
.
.Sh BUGS
You can tell me
about bugs you encountered
.Lk https://github.com/nakidai/tr2cyr/issues/new here .
